######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 4 11:39:30 2009
######################################################################

TEMPLATE = app
CONFIG += QtTest Dui DuiImServer duiimframework duireactionmap
DEPENDPATH += .
INCLUDEPATH += . \
		../stubs/


include(../common_check.pri)

LIBS += -Wl,-rpath=/usr/lib/dui-im-plugins/ -lduikeyboard

# Input
HEADERS += ut_duivirtualkeyboard.h \
           ../stubs/duigconfitem_stub.h \
           ../stubs/fakegconf.h \
           ../stubs/duireactionmaptester.h

SOURCES += ut_duivirtualkeyboard.cpp \
           ../stubs/fakegconf.cpp

