######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 8 16:15:36 2010
######################################################################
include(../common_top.pri)

TARGET = ut_wordribbondialog
TEMPLATE = app
CONFIG += meegotouch
LIBS += -Wl,-rpath=/usr/lib/meego-im-plugins/ -lmeego-keyboard

include(../common_check.pri)

HEADERS += ut_wordribbondialog.h
SOURCES += ut_wordribbondialog.cpp


