#!/bin/bash

### Generate Qt/C++ classes from template files.

HEADER_TMPL=header.tmpl
IMPL_TMPL=implementation.tmpl

MINIMUM_ARGS=2

ERROR_GENERAL=1
ERROR_BADARGS=65

### Functions
print_usage() {

    echo "Usage: `basename $0` class_name out_dir"
}

generate_class () {
    CLASS_NAME=$1
    OUT_DIR=$2
    CLASS_NAME_UPPER=$(echo "${CLASS_NAME}" | tr '[:lower:]' '[:upper:]')
    CLASS_NAME_LOWER=$(echo "${CLASS_NAME}" | tr '[:upper:]' '[:lower:]')

    cat ${HEADER_TMPL} | sed -e "s/%{class_name}/${CLASS_NAME}/g" \
                             -e "s/%{class_name.upper}/${CLASS_NAME_UPPER}/g" \
                             -e "s/%{class_name.lower}/${CLASS_NAME_LOWER}/g" \
                         > ${OUT_DIR}/${CLASS_NAME_LOWER}.h

    cat ${IMPL_TMPL}   | sed -e "s/%{class_name}/${CLASS_NAME}/g" \
                             -e "s/%{class_name.upper}/${CLASS_NAME_UPPER}/g" \
                             -e "s/%{class_name.lower}/${CLASS_NAME_LOWER}/g" \
                         > ${OUT_DIR}/${CLASS_NAME_LOWER}.cpp
}

### Main
if [ "$#" -lt "$MINIMUM_ARGS" ]
then
  print_usage
  exit $ERROR_BADARGS
fi

generate_class $1 $2
