######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 8 16:15:36 2010
######################################################################
include(../common_top.pri)

TARGET = ut_wordribbonitem
TEMPLATE = app
CONFIG += meegotouch

include(../common_check.pri)

LIBS += -Wl,-rpath=/usr/lib/meego-im-plugins/ -lmeego-keyboard

HEADERS += ut_wordribbonitem.h

SOURCES += ut_wordribbonitem.cpp


