usr/share/meegotouch/virtual-keyboard/layouts/zh_cn_cangjie.xml
usr/share/meegotouch/virtual-keyboard/layouts/zh_cn_pinyin.xml
usr/share/meegotouch/virtual-keyboard/layouts/zh_cn_zhuyin.xml
usr/share/meegotouch/virtual-keyboard/layouts/symbols_zh_cangjie.xml
usr/share/meegotouch/virtual-keyboard/layouts/hwsymbols_chinese.xml
usr/share/meegotouch/virtual-keyboard/layouts/symbols_zh_zhuyin.xml
usr/share/meegotouch/virtual-keyboard/layouts/symbols_zh_pinyin.xml
